version: "2"
services:
  master:
     domainname: rahona.be
     hostname: icinga2-master-1
     build: 
      context: ./base-master
     ports:
       - 5665:5665
     environment:
       - ICINGA2_USER_FULLNAME=Icinga2 Docker Monitoring Instance
     volumes:
       - /var/icinga2-master/cache:/var/cache/icinga2
       - /var/icinga2-master/certs:/etc/apache2/ssl:ro
       - /var/icinga2-master/etc/icinga2:/etc/icinga2
       - /var/icinga2-master/lib/icinga2:/var/lib/icinga2
       - /var/icinga2-master/lib/mysql:/var/lib/mysql
       - /var/icinga2-master/lib/php5/sessions:/var/lib/php5/sessions
       - /var/icinga2-master/log/apache2:/var/log/apache2
       - /var/icinga2-master/log/icinga2:/var/log/icinga2
       - /var/icinga2-master/log/mysql:/var/log/mysql
